---
title: "Data Transformation with dplyr"
author: "Alier Reng"
date: '2022-03-19'
output: html_document
---

## Loading the Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo    = TRUE,
  message = FALSE,
  warning = FALSE)

# Loading the Libraries
library(tidyverse)
library(readxl)
```

## Importing the Data

```{r}
# Importing the Data
path <- "../00_data/raw/multiple_sheets.xlsx"

ss_2008_census_raw <- path %>% 
  
  excel_sheets() %>% 
  set_names() %>% 
  map_df(read_excel, path = path, .id = "file name")
```

## Transforming the Data

```{r}
# Inspect the first rows
# head(ss_2008_census_raw)
slice_head(ss_2008_census_raw, n = 5)
```

```{r}
# Inspect the last 10 rows
# tail(ss_2008_census_raw)
slice_tail(ss_2008_census_raw, n = 10)
```

## Performing a Quick Summary

```{r}
aa <- ss_2008_census_raw %>% 
  skimr::skim()

aa
```

```{r}
ss_2008_census_tbl <- ss_2008_census_raw %>% 
  
  # Select Columns of Interest
  select(`Former Region`, ends_with("name"), `2008`)
  
```

```{r}
ss_2008_census_tbl <- ss_2008_census_raw %>% 
  
  # Select Desired Columns
  select(`Former Region`, contains("name"), population = `2008`)
```

```{r}
ss_2008_census_tbl <- ss_2008_census_raw %>% 
  
  # Select Columns of Interest
  select(2, 4, 7, 9, 12) %>% 
  
  # Rename the Columns
  # rename(population = `2008`)
  set_names("former region", "state", 
            "pop. category", "age category", 
            "population") %>% 
  
  # Fill in Blank Cells or NAS
  fill(`former region`,
       .direction = "down") %>% 
  
  # Modify the Pop Category
  separate(
    `pop. category`, 
    into = c("pop", "gender", "other"),
    sep = " "
  ) %>% 
  
  # Remove the Extra Columns
  select(-c(pop,other)) %>% 
  
  # Modify age category column
  mutate(
    `age category` = case_when(
      `age category` %in% c("0 to 4",  "5 to 9", "10 to 14")   ~ "0-14",
      `age category`  %in% c("15 to 19", "20 to 24")           ~ "15-24",
      `age category` %in% c("25 to 29", "30 to 34")            ~ "25-34", 
      `age category` %in% c("35 to 39", "40 to 44")            ~ "35-44",
      `age category` %in% c("45 to 49", "50 to 54")            ~ "45-54",
      `age category` %in% c("55 to 59", "60 to 64")            ~ "55-64",
      `age category` %in% c("65+")                             ~ "65+",
      TRUE ~ `age category`)
  ) %>% 
  
  # Remove Unwanted Rows
  filter(
    gender != "Total",
    `age category` != "Total"
  ) %>% 
  
  # Summarization and Group
  group_by(across(`former region`:`age category`)) %>% 
  summarize(
    population = sum(population),
    .groups    = "drop"
  )
```


## Converting our Scripts into a Function

```{r}
tweak_ss_census_data <- function(data, filter_var,
                                      group_var, pop_var, ...) {
  
  ss_census_tbl <- data %>% 
    
    # Select Columns of Interest
    select(...) %>% 
    
    # Rename the Columns
    set_names(
      "former region", "state", 
      "pop. category", "age category", 
      "population"
    ) %>% 
    
    # Fill in Blank Cells or NAS
    fill(`former region`,
         .direction = "down") %>% 
    
    # Modify the Pop Category
    separate(
      `pop. category`, 
      into = c("pop", "gender", "other"),
      sep = " "
    ) %>% 
    
    # Remove the Extra Columns
    select(-c(pop,other)) %>% 
    
    # Modify age category column
    mutate(
      `age category` = case_when(
        `age category` %in% c("0 to 4",  "5 to 9", "10 to 14")   ~ "0-14",
        `age category` %in% c("15 to 19", "20 to 24")            ~ "15-24",
        `age category` %in% c("25 to 29", "30 to 34")            ~ "25-34", 
        `age category` %in% c("35 to 39", "40 to 44")            ~ "35-44",
        `age category` %in% c("45 to 49", "50 to 54")            ~ "45-54",
        `age category` %in% c("55 to 59", "60 to 64")            ~ "55-64",
        `age category` %in% c("65+")                             ~ "65+",
        TRUE ~ `age category`)
    ) %>% 
    
    # Remove Unwanted Rows
    filter(
      gender != {{ filter_var }},
      `age category` != {{ filter_var }}
    ) %>% 
    
    # Summarization and Group
    group_by(across({{ group_var }})) %>% 
    summarize(
      "total_{{ pop_var }}" := sum({{ pop_var }}),
      .groups    = "drop"
    )
    
}
  
# dump("tweak_ss_census_data", "../R/data_transformation_functions.R")
```

```{r}
test_data <- ss_2008_census_raw %>% 
  
  tweak_ss_2008_census_data(
    filter_var = "Total",
    group_var  = c(`former region`:`age category`),
    pop_var    = population,
    `Former Region`, `Region Name`, `Variable Name`, `Age Name`,`2008`
    
  )

write_rds(test_data, "../00_data/wrangled/ss_census_data.tbl.rds")
```

## Tabulate South Sudan 2008 Census Data

```{r}
library(gt)

ss_census_gt <- 
  
  ss_2008_census_tbl %>% 
  
  # Modify Column Names
  janitor::clean_names() %>% 
  
  arrange(former_region) %>% 
  
  # Summarization and Group by
  group_by(former_region, state) %>% 
  summarize(
    total   = sum(population),
    .groups = "drop"
  ) %>% 
  
  # Initialize a gt Table
  gt(rowname_col = "former_region") %>% 
  
  # Formatting
  cols_align(
    columns = total,
    align   = "center"
  ) %>% 
  
  fmt_number(
    columns = total,
    sep_mark = ",",
    decimals = 0,
  ) %>% 
  tab_row_group(
    label = "Bahr el Ghazal",
    rows  = 1:4
  ) %>% 
  
  tab_row_group(
    label = "Equatoria",
    rows = 5:7
  ) %>% 
  
  tab_row_group(
    label = "Upper Nile",
    rows = 8:10
  ) %>% 
  
  # Add the Border Line
  tab_style(
    style = list(
      cell_borders(sides = "left", color = "darkgrey", weight = px(0.5))
    ),
    locations = cells_body(
      columns = total
    )
  ) %>% 
  
  # Modify Column Names
  tab_style(
    style = list(
      cell_text(transform = "capitalize")
    ),
    
    locations = cells_column_labels(everything())
  ) %>% 
  # Add the Title
  tab_header(
    title = "South Sudan 2008 Census Data by State"
  ) %>% 
  
  tab_options(heading.background.color = "grey"
  ) %>% 
  
  # Calculate Total Population
  grand_summary_rows(
    columns = total,
    fns = list(Total = ~ sum(.)),
    formatter = fmt_integer
  )

ss_census_gt

# Save the table
gtsave(ss_census_gt, "../00_images/ss_census_gt.html")
```

